apiVersion: v1
data:
  service_account_file: ViIbz3yGckfYYPWoiTcCui9quJGznyRLZcotBrKvRsE
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: 'true'
  labels:
    name: gke-pvm-killer
  name: gke-pvm-killer
  namespace: gke-pvm-killer
type: Opaque
