parameters:
  components:
    echo-server:
      replicas: 3
      vpa: Auto
      pdb_min_available: 2
      image: jmalloc/echo-server
      service:
        type: LoadBalancer
      healthcheck:
        type: http
        port: http
        probes: ['readiness']
        path: /_health
        timeout_seconds: 3
      ports:
        http:
          service_port: 80
          container_port: 8080
