apiVersion: v1
data:
  service_account_file: J1hoJ3NqNMJskxoIeR7isW6fJb9Ju_XH253k1sXn9PY
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: 'true'
  labels:
    name: postgres-proxy
  name: postgres-proxy
  namespace: postgres-proxy
type: Opaque
